---
- name: remove unnecessary packages
  apt:
    pkg:
      - avahi-daemon
      - htop
      - nano
      - ncdu
    state: absent
    purge: yes

- name: update apt cache and do safe upgrade
  apt:
    update_cache: yes
    upgrade: safe

- name: common apt housekeeping
  apt:
    autoremove: yes
    autoclean: yes

- name: enable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: started
    enabled: yes

- name: enable systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: yes

- name: ssh file in boot folder
  file:
    path: /boot/ssh
    state: touch

- name: /etc/hosts file
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
