---
- name: disable console keyboard setup service
  systemd:
    name: keyboard-setup.service
    enabled: "no"

- name: disable rc-local service
  systemd:
    name: rc-local.service
    enabled: "no"

- name: disable nfs-config service
  systemd:
    name: nfs-config.service
    enabled: "no"
