---
- name: set hostname
  hostname:
    name: zero

- name: copy hw config
  copy:
    src: boot/config.txt
    dest: /boot/config.txt

- name: copy network config
  copy:
    src: etc/systemd/network/zero-ethernet.network
    dest: /etc/systemd/network/zero-ethernet.network
    mode: 0644

- import_tasks: remove-unnecessary-packages.yaml
- import_tasks: pihole-services.yaml
- import_tasks: disable-services.yaml
