---
- name: set hostname
  hostname:
    name: zero

- name: remove unnecessary packages
  apt:
    pkg:
      - iw
      - pi-bluetooth
      - wpasupplicant
    state: absent
    purge: yes

- name: copy network config
  copy:
    src: etc/systemd/network/zero-ethernet.network
    dest: /etc/systemd/network/zero-ethernet.network
    mode: 0644
