---
- name: copy lighttpd external config
  copy:
    src: etc/lighttpd/external.conf
    dest: /etc/lighttpd/external.conf
    mode: 0644

- name: copy lighttpd fastcgi-php config
  copy:
    src: etc/lighttpd/conf-available/15-fastcgi-php.conf
    dest: /etc/lighttpd/conf-available/15-fastcgi-php.conf
    mode: 0644

- name: copy pihole update gravity timer
  copy:
    src: etc/systemd/system/pihole-update-gravity.timer
    dest: /etc/systemd/system/pihole-update-gravity.timer
    mode: 0644

- name: copy pihole update gravity service
  copy:
    src: etc/systemd/system/pihole-update-gravity.service
    dest: /etc/systemd/system/pihole-update-gravity.service
    mode: 0644

- name: enable pihole update gravity timer
  systemd:
    name: pihole-update-gravity.timer
    state: started
    enabled: "yes"

- name: enable pihole update gravity service
  systemd:
    name: pihole-update-gravity.service
    enabled: "yes"
