---
- name: remove unnecessary packages
  apt:
    pkg:
      - iw
      - pi-bluetooth
      - wpasupplicant
      - wireless-tools
      - rfkill
      - firmware-atheros
      - firmware-brcm80211
      - firmware-libertas
    state: absent
    purge: "yes"
